### ISSUE TITLE
TP ended

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/4a-isi3-tp1-2016-2017-groupe-1-de-la-comble_garin#1]
* 👎 Dans le rapport il manque un peu la présentation du design Iterator => à préciser donc.

* 👎 La méthode next est un peu redondante dans le BFS et DFS.

* 💡 Pourquoi pas ranger un peu en package

**Comment by flodlc** [comment]
Je viens de pusher la version finale en prenant en compte toutes les remarques.

**Comment by Slashgear** [comment]
C'est pas mal, mais pour info : 
* les noms de package en java sont en minuscule
* En général ils ne contiennent pas le mot package car on s'en doute un peu.

**Comment by flodlc** [comment]
D'accord, je prends note, merci pour le retour :)

**Comment by Slashgear** [comment]
C'est déjà bien mieux qu'en fin de première itération 👍
